---
shared:
  experimental_features: <%= ENV.fetch('EXPERIMENTAL_FEATURES', nil) %>
  self_destruct_value: <%= ENV.fetch('SELF_DESTRUCT', nil) %>
  software_update_url: <%= ENV.fetch('UPDATE_CHECK_URL', 'https://api.joinmastodon.org/update-check') %>
  source:
    base_url: <%= ENV.fetch('SOURCE_BASE_URL', nil) %>
    repository: <%= ENV.fetch('GITHUB_REPOSITORY', 'polyamspace/mastodon') %>
    tag: <%= ENV.fetch('SOURCE_TAG', nil) %>
  version:
    metadata: <%= ['glitch', 'polyam', ENV.fetch('MASTODON_VERSION_METADATA', nil)].compact_blank.join('.') %>
    prerelease: <%= ENV.fetch('MASTODON_VERSION_PRERELEASE', nil) %>
