# This file contains default values, and does not need to be edited. All
# important settings can be changed from the admin interface.

defaults: &defaults
  site_title: 'Mastodon Polyam Edition'
  site_short_description: ''
  site_description: ''
  site_extended_description: ''
  site_terms: ''
  site_contact_username: ''
  site_contact_email: ''
  registrations_mode: 'none'
  profile_directory: true
  closed_registrations_message: ''
  timeline_preview: false
  show_staff_badge: true
  preview_sensitive_media: false
  show_application: false
  noindex: false
  norss: false
  flavour: 'polyam'
  skin: 'system'
  system_dark: 'default'
  system_light: 'mastodon-light'
  trends: true
  trends_as_landing_page: false
  trendable_by_default: false
  trending_status_cw: true
  trending_status_sensitive: true
  hide_followers_count: false
  reserved_usernames:
    - abuse
    - account
    - accounts
    - admin
    - administration
    - administrator
    - admins
    - help
    - helpdesk
    - instance
    - mod
    - moderator
    - moderators
    - mods
    - owner
    - root
    - security
    - server
    - staff
    - support
    - webmaster
  disallowed_hashtags: # space separated string or list of hashtags without the hash
  bootstrap_timeline_accounts: ''
  activity_api_enabled: true
  peers_api_enabled: true
  show_reblogs_in_public_timelines: false
  show_replies_in_public_timelines: false
  default_content_type: 'text/plain'
  show_domain_blocks: 'disabled'
  show_domain_blocks_rationale: 'disabled'
  outgoing_spoilers: ''
  require_invite_text: false
  backups_retention_period: 7
  search_preview: false
  invite_text_filter: ''
  publish_button_text: ''
  captcha_enabled: false
  allow_referer_origin: false
  reject_pattern: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
