# frozen_string_literal: true

# Polyam helper to convert Material icon names to FA icon names

module IconHelper
  MATERIAL_TO_FA = {
    account_circle: 'circle-user',
    add: 'plus',
    alternate_email: 'envelope',
    arrow_right_alt: 'arrow-right',
    arrow_left_alt: 'arrow-left',
    arrow_upward: 'arrow-up',
    arrow_downward: 'arrow-down',
    breaking_news: 'newspaper',
    brush: 'broom',
    campaign: 'bullhorn',
    captive_portal: 'arrow-right-arrow-left',
    chat: 'comment',
    chat_bubble: 'comments',
    check: 'check',
    chevron_left: 'chevron-left',
    chevron_right: 'chevron-right',
    close: 'xmark',
    cloud: 'cloud',
    cloud_download: 'cloud-arrow-down',
    cloud_sync: 'cloud-arrow-down',
    cloud_upload: 'cloud-arrow-up',
    code: 'code',
    comment: 'comment',
    computer: 'computer',
    contact_mail: 'address-card',
    content_copy: 'copy',
    database: 'database',
    delete: 'trash',
    description: 'file-lines',
    desktop_mac: 'computer',
    diamond: 'gem',
    download: 'download',
    edit: 'pencil', # Also pen-to-square
    feedback: 'comment',
    flag: 'flag',
    filter_alt: 'filter',
    format_paragraph: 'paragraph',
    gavel: 'gavel',
    globe: 'globe',
    group: 'users',
    groups: 'users',
    hide_source: 'ban',
    history: 'clock-rotate-left',
    hourglass: 'hourglass-half',
    inbox: 'inbox',
    info: 'circle-info',
    key: 'key',
    keyboard_double_arrow_down: 'angles-down',
    link: 'link',
    link_off: 'link-slash',
    list: 'bars',
    list_alt: 'list',
    lock: 'lock',
    lock_open: 'lock-open',
    logout: 'right-from-bracket',
    mail: 'envelope',
    manufacturing: 'gears',
    menu: 'bars',
    mood: 'face-smile',
    more_horiz: 'ellipsis',
    open_in_new: 'arrow-up-right-from-square',
    person: 'user',
    person_add: 'user-plus',
    person_remove: 'user-xmark',
    photo_camera: 'camera',
    power_off: 'power-off',
    radio_button_checked: 'power-off',
    radio_button_unchecked: 'power-off',
    refresh: 'rotate-left',
    repeat: 'boost',
    reply: 'reply',
    safety_check: 'mobile-screen',
    save: 'floppy-disk',
    search: 'magnifying-glass',
    settings: 'gear',
    smartphone: 'mobile-screen',
    speed: 'gauge-high',
    'star-fill': 'star',
    sync_alt: 'arrow-right-arrow-left',
    tag: 'hashtag',
    toggle_off: 'toggle-off',
    toggle_on: 'toggle-on',
    trending_up: 'arrow-trend-up',
    tune: 'sliders',
    visibility: 'eye',
    visibility_off: 'eye-slash',
    warning: 'triangle-exclamation',
  }.freeze

  def fa_icon(icon)
    MATERIAL_TO_FA[icon.to_sym]
  end
end
