---
el:
  simple_form:
    glitch_only: glitch-soc
    labels:
      defaults:
        setting_default_content_type: Προεπιλεγμένη μορφή για τουτς
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Απλό κείμενο
        setting_show_followers_count: Δείξε τον αριθμό των ακολούθων σου
