---
lt:
  simple_form:
    glitch_only: "„glitch-soc“"
    hints:
      defaults:
        setting_default_content_type_html: Rašant įrašus, manyti, kad jie parašyti neapdorotu HTML, nebent nurodyta kitaip.
        setting_default_content_type_markdown: Rašant įrašus, manyti, kad jie naudoja ženklinimą raiškiam teksto formatavimui, nebent nurodyta kitaip.
        setting_default_content_type_plain: Rašant įrašus manyti, kad jie yra grynas tekstas be ypatingo formatavimo, nebent nurodyta kitaip (numatytoji „Mastodon“ elgsena).
        setting_default_language: Įrašų kalba gali būti aptikta automatiškai, bet tai ne visada tiksliai.
        setting_show_followers_count: Rodykite sekėjų skaičių savo profilyje. Jei slėpsite sekėjų skaičių, jis bus paslėptas net nuo jūsų pačių, o kai kurios programos gali rodyti neigiamą sekėjų skaičių.
        setting_skin: Iš naujo pridėta pasirinktą „Mastodon“ atmainą
    labels:
      defaults:
        setting_default_content_type: Numatytasis įrašų formatas
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Ženklinimas
        setting_default_content_type_plain: Grynasis tekstas
        setting_favourite_modal: Rodyti patvirtinimo dialogo langą prieš pamėgant (taikoma tik „Glitch“ atmainiui)
        setting_show_followers_count: Rodyti savo sekėjų skaičių
        setting_skin: Apipavidalinimas
        setting_system_emoji_font: Naudoti numatytąjį sistemos šriftą jaustukams (taikoma tik „Glitch“ atmainiui)
      notification_emails:
        trending_link: Nauja tendencinga nuoroda reikia peržiūros
        trending_status: Naujas tendencingas įrašas reikia peržiūros
        trending_tag: Nauja tendencinga žymė reikia peržiūros
